version: '3.8'

services:
  web:
    build: .
    command: python manage.py test
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    environment:
      - DATABASE_URL=postgres://education_user:your_secure_password@db:5432/education_db
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=education_db
      - POSTGRES_USER=education_user
      - POSTGRES_PASSWORD=your_secure_password
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
