services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 && python manage.py migrate
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=education_db
      - POSTGRES_USER=education_user
      - POSTGRES_PASSWORD=your_secure_password
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
